<?php Print Form::open() ?>
  <div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
      <h3>Crear Usuarios</h3>
  </div>

  <div class="modal-body">
    <div class="span4">
      <label>Nombre de Usuario</label>
      <?php Print Form::text("usuarios.usuario", "class='span4'") ?>
    </div>
    
    <div class="span4">
      <label>Email</label>
      <?php Print Form::text("usuarios.email", "class='span4'") ?>
    </div>

    <div class="span4">
      <label>Contraseña</label>
      <?php Print Form::pass("usuarios.pass1", "class='span4'") ?>
    </div>

    <div class="span4">
      <label>Repita Contraseña</label>
      <?php Print Form::pass("usuarios.pass2", "class='span4'") ?>
    </div>

    <div class="span4">
      <label>Rol de Usuario</label>
      <?php Print Form::select("usuarios.rol", $rols) ?>
    </div>
  </div>

  <div class="modal-footer">
    <?php Print Form::submit('Salvar Cambios', "class='btn btn-primary'") ?>
    <!--<a class="btn btn-primary" onclick="$('.modal-body > form').submit();">Guardar Cambios</a>-->
    <a class="btn" data-dismiss="modal">Close</a>
  </div>
<?php Print Form::close() ?>
<?php View::content() ?>