<div id="scaffold">
<?php View::partial('bootstrap/modal') ?>
<?php View::content()?>
<?php if ($results->items) : ?>

<div class="well">
    <?php echo Html::linkAction("crear/","<i class='icon-plus-sign'></i> Crear registro", "class='btn btn-primary' class='add' data-toggle='modal' data-target='#myModal'")?>
</div>
<table class="table table-hover table-bordered dataTable">
    <thead><tr>
    <?php foreach (current($results->items)->fields as $field) : ?>
        <th><?php Print (current($results->items)->get_alias($field))?></th>
    <?php endforeach?>
	<th>Acciones</th>
    </tr></thead>
	<tbody>
    <?php foreach ($results->items as $item) : ?>
        <tr>
            <?php foreach ($item->fields as $field) : ?>
            <td><?php eh($item->$field)?></td>
            <?php endforeach?>
			<td>
            <?php echo Html::linkAction("ver/$item->id","<i class='icon-eye-open'></i>")?> |
			<?php echo Html::linkAction("editar/$item->id","<i class='icon-edit'></i> Editar", "class='edit' data-toggle='modal' data-target='#myModal'")?> |
			<?php echo Html::linkAction("borrar/$item->id",'<i class="icon-trash"></i>Borrar', 'onclick="return confirm(\'¿Está seguro?\')"')?>
			</td>
        </tr>
    <?php endforeach?>
	</tbody>
</table>
<div class="well">
<?php View::partial('paginator/classic', false, array('page' => $results ,'url' => Router::get('controller_path').'/index')); ?>
</div>

<?php else : // Si no hay items?>
<h2>No hay ningún registro</h2>
<?php endif ?>

</div>

<?php //var_dump($results)?>
