
<div id="scaffold">
<?php View::content()?>
	<div class="actions well">
		<a class="btn btn-inverse" href="../">Listado</a>
		<a class="btn btn-primary" href="../crear/">Crear registro</a>
		<a class="btn" href="../editar/<?php echo $result->id?>">Editar</a>
		<a class="del btn btn btn-danger" title="¿Seguro que quiere borrar?" href="../borrar/<?php echo $result->id?>" onclick="return confirm('¿Está seguro?');">Borrar</a>
	</div>
<?php if($result) : ?>
	<ul>
	<?php foreach ($result->fields as $field) : ?>
		<li><strong><?php echo $result->alias[$field]?> :</strong>  <?php eh($result->$field) ?></li>
	<?php endforeach ?>
	</ul>
<?php else : ?>
	<?php header("HTTP/1.0 404 Not Found")?>
	<h1>No existe</h1>
	<div class="actions">
		<a href="../">Listado</a>
		<a href="../crear/">Crear registro</a>
	</div>
<?php endif ?>
	<pre><?php //var_dump($result)?></pre>
	</div>
